version: '3'
services:
  backend:
    image: viniciussoares18/sf-back:v1
    ports:
      - "8443:8443"
  nginx:
    image: nginx:latest
    volumes:
      - /home/ubuntu/safe-food-infra-resources/ssl:/etc/nginx/ssl
      - /home/ubuntu/safe-food-infra-resources/docker-compose/for_back/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
    depends_on:
      - backend